function [trialInfo, pathData, pathDataIdeal, pathDataLin] = loadPathInfo_Treadmill(sessInfo,extractMode)
%LOADINFO Load session information from each block directory
%
% [trialInfo,pathData, pathDataIdeal, pathDataLin] = LOADINFO(sessInfo, i, extractMode)
%
% The output arguemtns will each be a struct with block names (e.g.
% nodelay, delay10, etc) as fields and contain information generated by the
% preprocessing script |preprocessPathData.m|.
% 
% |trialInfo| will contain information such as DIRECTION, SUCCESS,
% LOCATIONS, START_END_TIMESTAMPS, etc
% 
% |parsingInfo| is a subst of |trialInfo| containing the most relevant
% information.
%
% |pathData|, |pathDataIdea|, and |pathDataLin| are processed video
% tracking data.


if ~exist('extractMode', 'var') || isempty(extractMode)
	extractMode = 'struct';
end

SessDirs = sessInfo.sessDirs;

trialInfo = cellfun(@(bl) load(fullfile(sessInfo.mainDir, bl, 'trialInfo.mat')), SessDirs, 'un', 0);
pathData = cellfun(@(bl) load(fullfile(sessInfo.mainDir, bl, 'pathdata.mat')), SessDirs, 'un', 0);

% parsingInfo = cellfun(@(bl) load(fullfile(sessInfo.mainDir, bl, 'parsingInfo.mat')), SessDirs, 'un', 0);
pathDataIdeal = cellfun(@(bl) load(fullfile(sessInfo.mainDir, bl, 'pathDataIdeal.mat')), SessDirs, 'un', 0);
pathDataLin = cellfun(@(bl) load(fullfile(sessInfo.mainDir, bl, 'pathDataLinear.mat')), SessDirs, 'un', 0);


if strcmpi(extractMode, 'struct')
	trialInfo = cell2structure(trialInfo, SessDirs);
% 	parsingInfo = cell2structure(parsingInfo, SessDirs);
	pathData = cell2structure(pathData, SessDirs);
	pathDataIdeal = cell2structure(pathDataIdeal, SessDirs);
	pathDataLin = cell2structure(pathDataLin, SessDirs);
elseif strcmpi(extractMode, 'cell')
	% pass
end
end

function S = cell2structure(C, fields)

C = cellfun(@(c) c, C, 'un', 0);

args = cell(length(C)*2, 1);
args(1:2:end) = fields;
args(2:2:end) = C;

S = struct(args{:});
end